### ISSUE TITLE
[Design Services page]: Section 01: Creating future-shaping experiences

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#105]
Replace two image approach to the one of the ones below in section 02 or 03. Meaning an image spanning across (16:9) or one large with a smaller one (16:9 with 1:1 or smaller 16:9).

**Comment by mjabbink** [comment]
not like this...

![screen shot 2019-01-22 at 1 13 31 pm](https://user-images.githubusercontent.com/32881239/51556407-19275f00-1e48-11e9-91ed-90e4c5338f38.png)

**Comment by mjabbink** [comment]
but like one of these...

![screen shot 2019-01-22 at 1 17 09 pm](https://user-images.githubusercontent.com/32881239/51556418-22b0c700-1e48-11e9-92cd-29338556fcf1.png)

**Comment by mjabbink** [comment]
but use 16:9 aspect ratio.

![screen shot 2019-01-22 at 1 17 14 pm](https://user-images.githubusercontent.com/32881239/51556424-26dce480-1e48-11e9-8a6d-48cc0d87062b.png)

**Comment by alisonjoseph** [comment]
@RyanCaruthers can this be closed since its been addressed in #134 ?

**Comment by RyanCaruthers** [comment]
Yes close this, since that page got a redesign. Thank you!
