### ISSUE TITLE
[top nav]: color specs

### ISSUE THREAD

**Issue by sadekbazaraa** [IBM-Design/design-website#106]
I noticed that the hover color for Approach was different than for the other links. Sharing colors for the various states including, hover, selected, etc.

![screen shot 2019-01-22 at 1 32 21 pm](https://user-images.githubusercontent.com/33162280/51557309-90f68900-1e4a-11e9-9e6b-acbcb6c94863.png)

@alisonjoseph @RyanCaruthers

**Comment by alisonjoseph** [comment]
This was the spec provided by @jeanservaas 

https://github.com/IBM-Design/design-website/issues/22

**Comment by sadekbazaraa** [comment]
Thanks @alisonjoseph I'm going to loop back around with her and see where we're at.

**Comment by alisonjoseph** [comment]
There is still some confusion around what needs to get updated here.

**Comment by mjabbink** [comment]
@alisonjoseph Sorry about confusion. Working to a detail for lead space color but the top nav bar should be Grey 100 which I think you have correct.

We’re having final discussion on lead space being Black #000000

**Comment by alisonjoseph** [comment]
should the hover color for approach be updated?

**Comment by sadekbazaraa** [comment]
Hi Alison, yes. There's a handful to top nav changes. We've been holding off to try and get you everything spec'd out at once. There's been lots of chats behind the scenes today but we're hoping to get this over to you shortly.

**Comment by alisonjoseph** [comment]
perfect! appreciate the consolidation of issues 👍

**Comment by sadekbazaraa** [comment]
Hi @alisonjoseph — I slacked you that Mike and I just got off a nav review with the dotcom team and came to a good consensus which means we have a few updates. SORRY! I know you just closed this issue. This should be the last.

![screen shot 2019-01-28 at 1 20 05 pm](https://user-images.githubusercontent.com/33162280/51857394-21781200-2300-11e9-9536-f6866f0ecc16.png)

We're eliminating the 16px spacer that was at the top of the previous dropdown. And instead of 40px containers for the links, everything has a 48px container. This syncs up with dotcom.

![screen shot 2019-01-28 at 1 20 17 pm](https://user-images.githubusercontent.com/33162280/51857484-60a66300-2300-11e9-976f-eb895657c07a.png)

We've gone back to 4px for the selected state blue underline so that it shows up better in multiple scenarios. Here you can see an example of hover state on 'Overview' and selected state on 'Design Philosophy'.

![screen shot 2019-01-28 at 1 20 30 pm](https://user-images.githubusercontent.com/33162280/51857690-e3c7b900-2300-11e9-8d23-a37219efd558.png)

And here you can see the hover state on 'Impact' and the selected state on 'Approach'. Notice that the selected state just has the blue underline and not that lighter background field.

FYI @jeanservaas @mjabbink @RyanCaruthers

**Comment by RyanCaruthers** [comment]
@sadekbazaraa Sounds good on my end! Gonna look great!

**Comment by mjabbink** [comment]
looks like the blue bar got lost in the update

**Comment by alisonjoseph** [comment]
Where aren't you seeing the blue bar?

**Comment by sadekbazaraa** [comment]
the blue bar is showing up for me just fine in both chrome and safari

**Comment by mjabbink** [comment]
it’s in there now. All good.
