### ISSUE TITLE
Photos containers updated On top half of Teams page

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#110]
Hey team, we have got some images now for the teams page near the top, so please add in the allowance for these 12 individual images... see attached
![screen shot 2019-01-23 at 9 35 26 am](https://user-images.githubusercontent.com/46679352/51618069-28afb200-1ef3-11e9-8b1d-096214483dc7.png)
![screen shot 2019-01-23 at 9 35 39 am](https://user-images.githubusercontent.com/46679352/51618070-28afb200-1ef3-11e9-8a13-b4d693b71161.png)
![screen shot 2019-01-23 at 9 35 49 am](https://user-images.githubusercontent.com/46679352/51618071-28afb200-1ef3-11e9-916e-4bb7f66cc204.png)

**Comment by RyanCaruthers** [comment]
refer to latest sketch file for all tablet and mobile guidance

https://ibm.box.com/s/5wc99pfadnbgae6sak4ve3m41gwf1f0l

**Comment by alisonjoseph** [comment]
done! thanks @designertyler! (image quality fix in open PR)
