### ISSUE TITLE
Down Arrows need to be Plex arrows

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#114]
<img width="397" alt="screen shot 2019-01-23 at 1 09 16 pm" src="https://user-images.githubusercontent.com/46679352/51630603-30ca1a80-1f10-11e9-9758-33204f672311.png">

**Comment by alisonjoseph** [comment]
what is the character for this? what font size?

**Comment by RyanCaruthers** [comment]
Mike says you need this unicode, and that if you put the unicode it, then it should create the arrow. And the size in sketch file is at 32

↓ U+2193
U+2193 is the unicode for that down arrow
