### ISSUE TITLE
[Approach]: Design Thinking Framework lead space

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#117]
@RyanCaruthers The image/video should be at the center point of lead space not going over right? Not sure your intent for these. Your Sketch implies center and animations blending in with the background. Is this still the goal? Where are these animations/videos coming from?

<img width="1514" alt="screen shot 2019-01-23 at 2 33 12 pm" src="https://user-images.githubusercontent.com/32881239/51632036-50ffd680-1f1c-11e9-8b5c-d10768506b38.png">

**Comment by RyanCaruthers** [comment]
yes that intent is correct, to be centered horizontally in the lead space when video is playing with subtle image in background.... see attached of intent....

these videos will be all from vimeo:
1)the ethos animation (same as the IDL site)
2)The EDT video, same one that team will have on their site
3)Current iX video that is on their site.


<img width="1118" alt="screen shot 2019-01-23 at 1 53 11 pm" src="https://user-images.githubusercontent.com/46679352/51633020-4f331480-1f16-11e9-8f48-2cac647c8b7c.png">

**Comment by RyanCaruthers** [comment]
@mjabbink above

**Comment by RyanCaruthers** [comment]
see attached for tablet and mobile.


<img width="1064" alt="screen shot 2019-01-23 at 1 56 03 pm" src="https://user-images.githubusercontent.com/46679352/51633325-062f9000-1f17-11e9-9146-23a65247374e.png">

**Comment by alisonjoseph** [comment]
👍do you have the vimeo links?

**Comment by RyanCaruthers** [comment]
getting those in an hour, wil share then

**Comment by RyanCaruthers** [comment]
Headers on these pages are
Desktop: 560
Talet: 336
Mobile: 480

**Comment by RyanCaruthers** [comment]
i think i may have made a seperate issue for these also regarding how the videos play....just FYi, the look of the video player above is not correct.

**Comment by mjabbink** [comment]
@RyanCaruthers 
— can you send me links to these videos

and are we going with overlay like in the Watson example? https://msc-watson-64-qms6lkgtrcnynocvo1qetkrujywaeokg.tugboat.qa/watson/ai-for-contract-governance

**Comment by RyanCaruthers** [comment]
Yes we are going with the overlay look. That is what i have requested already..

Links:
https://vimeo.com/304672438
https://vimeo.com/313055439
https://vimeo.com/303560967/c6d41539cd
https://www.youtube.com/watch?v=J727tCXTggk

**Comment by mjabbink** [comment]
Do we have access to the EDT source files? The production quality is poor at best. Some of the folks shot on blue are muted, not contrast and midtowns are all filed up. A few are nice and bright. It’s exactly what I was worried about. Good content, good story board narrative, but mediocre in it’s execution and production quality.

**Comment by mjabbink** [comment]
The only thing we could do wit his is help with color filtering to try to even out the peeps showing up on blue.
