### ISSUE TITLE
[Approach]: Use apostrophe in opening para just under lead space

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#118]
should be  we’re

![screen shot 2019-01-22 at 1 10 55 pm](https://user-images.githubusercontent.com/32881239/51632165-a3d98e00-1f1c-11e9-9c2d-b82329d1f007.png)

**Comment by alisonjoseph** [comment]
fixed (issue was caused by this text being wrapped in a custom component not markdown, anything in markdown should automatically display the correct quote)
