### ISSUE TITLE
[Global]: Link color on black should go one notch lighter blue

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#119]
<img width="302" alt="screen shot 2019-01-23 at 3 00 22 pm" src="https://user-images.githubusercontent.com/32881239/51633501-c4efae00-1f1f-11e9-976e-b9d34fafd080.png">

**Comment by alisonjoseph** [comment]
This is done, links are now blue-40 on gray-100 background (might need to clear cache or view in incognito if you aren't seeing it for some reason)
