### ISSUE TITLE
[global] Safari: arrows ↳ are not Plex

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#124]
In mobile too. Same for carbon

**Comment by alisonjoseph** [comment]
<img width="1171" alt="screen shot 2019-01-24 at 11 42 15 am" src="https://user-images.githubusercontent.com/2753488/51700394-a697ba00-1fd4-11e9-9935-00eae98f194c.png">

Safari on left, chrome on the right. The `:before` element seems to be ignoring the font-face styles.

**Comment by mattrosno** [comment]
@mjabbink @alisonjoseph I don't think this has anything to do with Safari. The correct characters were shown on my computer across Chrome/Safari/Firefox, and then when disabling my locally-installed Plex fonts, all three browsers now show the image on the left. Also makes sense why Mobile Safari wouldn't show the arrow characters.

I'd check to see if those characters are included in the Plex that the Carbon website is consuming.

**Comment by mjabbink** [comment]
We never made web fonts without the arrow sets so I don’t think that is a possibility but safe to double check.

**Comment by mjabbink** [comment]
Carbon should be consuming the latest packages from Github.

**Comment by mjabbink** [comment]
That explains why the Serif is the old one in certain places which I created an issue for. Google has not updated since firs releases. 

Does not explain arrows as they have them in the fonts Google has. Hmm
