### ISSUE TITLE
[Approach] Design Thinking page - text 2

### ISSUE THREAD

**Issue by philgilbertsr** [IBM-Design/design-website#129]
Change the second paragraph of text from: "We built on that idea, adding strategies, tactics and activities to create a framework uniquely tailored to address the challenges and scale of the modern enterprise."

To:

We built on that idea, adding unique strategies, tactics and activities to create a framework that uniquely scales design thinking across teams of all shapes and sizes, whether they are co-located or widely dispersed.

**Comment by mbiyimoh** [comment]
Addressed in pull request #132
