### ISSUE TITLE
[Philosophy] Remove side bar copy in mobile / tighten spacing

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#139]
<img width="494" alt="screen shot 2019-01-24 at 1 04 18 pm" src="https://user-images.githubusercontent.com/32881239/51698942-90402d00-1fd9-11e9-9430-24457d81d593.png">

**Comment by mjabbink** [comment]
@RyanCaruthers Spacing seems excessive

<img width="958" alt="screen shot 2019-01-24 at 1 09 39 pm" src="https://user-images.githubusercontent.com/32881239/51698972-a221d000-1fd9-11e9-9d02-e7a87dcf7c53.png">

**Comment by mjabbink** [comment]
<img width="905" alt="screen shot 2019-01-24 at 1 09 44 pm" src="https://user-images.githubusercontent.com/32881239/51698988-a817b100-1fd9-11e9-9124-e47cdc80058a.png">

**Comment by mjabbink** [comment]
in mobile the quote should adhere to the same right side margin


<img width="398" alt="screen shot 2019-01-24 at 1 14 09 pm" src="https://user-images.githubusercontent.com/32881239/51699147-017fe000-1fda-11e9-964f-d7e176021325.png">

**Comment by RyanCaruthers** [comment]
@alisonjoseph  The space between each set of content should only be 80px
