### ISSUE TITLE
[Vimeo UI elements]

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#144]
We should strip away everything we can in vimeo preferences. See IDL site. We removed their blue hover and went with black and white. We removed their logo as well.

**Comment by mjabbink** [comment]
remove color, logo, etc.

<img width="869" alt="screen shot 2019-01-24 at 2 30 00 pm" src="https://user-images.githubusercontent.com/32881239/51703648-e36bad00-1fe4-11e9-9b75-d47586932085.png">

**Comment by mjabbink** [comment]
<img width="1198" alt="screen shot 2019-01-24 at 2 30 30 pm" src="https://user-images.githubusercontent.com/32881239/51703697-06965c80-1fe5-11e9-965a-8178bdb80966.png">

**Comment by mjabbink** [comment]
@RyanCaruthers Sadek can help do this with you.

**Comment by RyanCaruthers** [comment]
@mjabbink I already have an issue for this stuff

**Comment by RyanCaruthers** [comment]
Hey all, i'm gonna make an executive design decision and scrap the three videos at the top of these Approach child pages for now.... We can add this idea to a back log for possible future releases....

Thank you.
