### ISSUE TITLE
Type size update: Cards at bottom of the three approach child pages

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#156]
update the type size of the headline to be "Expressive-heading-05" 48px Sans Light

see attached from sketch file...

![screen shot 2019-01-24 at 3 22 30 pm](https://user-images.githubusercontent.com/46679352/51709536-444ab380-1fec-11e9-9338-5890dc2a55ac.png)

**Comment by mjabbink** [comment]
@RyanCaruthers looks good!

**Comment by alisonjoseph** [comment]
Hey @RyanCaruthers , this type token is too big, text gets cut off when you start scaling the browser down to tablet size. See screenshots at desktop and tablet. We can review in person.

<img width="797" alt="screen shot 2019-01-24 at 11 14 09 pm" src="https://user-images.githubusercontent.com/2753488/51726603-d030ff80-202d-11e9-8e7a-b64294f79075.png">
<img width="1435" alt="screen shot 2019-01-24 at 11 13 53 pm" src="https://user-images.githubusercontent.com/2753488/51726604-d030ff80-202d-11e9-84b7-7681738c4e8b.png">

**Comment by alisonjoseph** [comment]
It does scale down, just not enough to fit in that small space we have at tablet.

**Comment by RyanCaruthers** [comment]
Ah ok can we apply the next scale down in the tokens then, so it still has as much of the larger size look as possible?

**Comment by alisonjoseph** [comment]
They are the next token size down 🤷‍♀️  --  do we need another token maybe in between?

**Comment by RyanCaruthers** [comment]
ah ok lets leave it for now and bring that up in the meeting with group later

**Comment by jeanservaas** [comment]
Not quite sure what the ish, is... can i see it in person?

**Comment by RyanCaruthers** [comment]
ok @alisonjoseph lets look at this life together.

**Comment by RyanCaruthers** [comment]
@alisonjoseph We are gonna apply "Expressive- Heading 05" to MAX, XLG, and LRG

"Expressive Paragraph 01" to both Tablet and Mobile


So a token switch at these breakpoints

**Comment by alisonjoseph** [comment]
Got it 👍
