### ISSUE TITLE
Iphone issues

### ISSUE THREAD

**Issue by philgilbertsr** [IBM-Design/design-website#174]
I’ve attached three screen shots from iPhone XS Max. I think we really need someone to focus solely on mobile design and intention. 

Landing page of the site is unattractive with mostly a black screen. The rebus is down low and the bold statement text is half off screen, and not in an intentional way. 

There are issues with the videos. When they show up, they don’t run, but you see the Vimeo video bar on screen, in situ. Very unattractive. 
![0217cfe0-bc54-44d2-bedf-48eea0a58a5c](https://user-images.githubusercontent.com/5391231/51737575-d900f000-2084-11e9-9574-38fef1a4ad09.png)
![c0316b47-8989-4619-9be5-a4524d4dafeb](https://user-images.githubusercontent.com/5391231/51737576-d900f000-2084-11e9-88df-863f0314250c.png)
![4c28080f-a101-49f4-a8de-b02700ed8c9f](https://user-images.githubusercontent.com/5391231/51737577-d900f000-2084-11e9-8f3e-19b9c888a79e.png)

Third, when you scroll down it just doesn’t snap to anything, and you can easily get to a place where it just looks like a jumble of stuff.

**Comment by alisonjoseph** [comment]
The mobile intent is for the black box to fill the screen, its getting pushed down too far and we are working on cleaning that up. Screen shot from the sketch file.
<img width="323" alt="screen shot 2019-01-25 at 7 19 05 am" src="https://user-images.githubusercontent.com/2753488/51748295-94b82480-2071-11e9-9ffe-f6b8834e99a1.png">

The video embeds have several issues around them and are being actively worked on also. 

Is there an example site somewhere that snaps in the way you are talking about?
