### ISSUE TITLE
EDT video

### ISSUE THREAD

**Issue by philgilbertsr** [IBM-Design/design-website#175]
The EDT video needs work. From a story perspective I think it’s good. But it just ends weird and doesn’t look like anyone finished the editing. Where’s the ending bumper. It needs one. But more important it’s like we cut Eunice off mid sentence. It feels like we just ran out of time to finish. 

From a design perspective it’s probably sub standard. The stock photography feels out of touch with the IBM people sections. It FEELS like stock footage where we used, well, stock footage. 

So this needs work ASAP to be included. (Also, note the Vimeo bar, as previously reported. This is happening to all videos on the iPhone)
![c2749199-4f44-41f9-8aff-32936a31a7f0](https://user-images.githubusercontent.com/5391231/51738020-0bf7b380-2086-11e9-811c-0bbeab21898b.png)

**Comment by RyanCaruthers** [comment]
@philgilbertsr @alisonjoseph I agree with those points, We have asked all teams to share with us approved content. So we assume you and other stakeholders have been involved to approve that. I say we simply pull this specific video then. That team will need to get this direction from us and possibly link to their video at a future date.

**Comment by RyanCaruthers** [comment]
Hey all, i'm gonna make an executive design decision and scrap the three videos at the top of these Approach child pages for now.... We can add this idea to a back log for possible future releases....

Thank you.
