### ISSUE TITLE
[Design Thinking iconography]: update with proper icons

### ISSUE THREAD

**Issue by mbiyimoh** [IBM-Design/design-website#176]
Approach - Design Thinking page: the icons below the 3 items in the Principles, Loop and Keys  are all the same right now. need to update with the appropriate icons

**Comment by RyanCaruthers** [comment]
@mbiyimoh This is updated in sketch and i believe Tyler Tate is tackling it this morning

**Comment by designertyler** [comment]
You can preview these added icons here https://deploy-preview-183--design-website.netlify.com/approach/design-thinking

**Comment by RyanCaruthers** [comment]
Thanks Tyler! Looks great! @designertyler

**Comment by RyanCaruthers** [comment]
This is being addressed as a PR so im gonna close this

**Comment by mbiyimoh** [comment]
Howdy, just noticed that the icons for "A focus on user outcomes" and "Diverse empowered teams" are backwards. Single circle should be for user outcomes, 3 circles for diverse teams

**Comment by mbiyimoh** [comment]
@designertyler 🔥🔥🔥
