### ISSUE TITLE
[Impact]: Two cards have straight apostrophe (') 

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#194]
Change from ( ' )  to (  ‘  ).

<img width="371" alt="screen shot 2019-01-25 at 5 40 04 pm" src="https://user-images.githubusercontent.com/32881239/51776784-9fea6f00-20c8-11e9-85e1-9cefc43f840d.png">

———

<img width="361" alt="screen shot 2019-01-25 at 5 40 37 pm" src="https://user-images.githubusercontent.com/32881239/51776789-a7117d00-20c8-11e9-903d-340cd0c4d941.png">

**Comment by mjabbink** [comment]
@alisonjoseph @RyanCaruthers also been chatting with jeanners on this but we think the type in the cards in impact should be 16px to not run into these issues below in smaller breakpoints


<img width="478" alt="screen shot 2019-01-25 at 5 39 33 pm" src="https://user-images.githubusercontent.com/32881239/51776877-f2c42680-20c8-11e9-94f2-b5118f997eda.png">

**Comment by mjabbink** [comment]
same for home page cards too. Any editorial based card should be 16px I reckon. I think the ones on approach landing are OK as is though.


<img width="771" alt="screen shot 2019-01-25 at 5 48 25 pm" src="https://user-images.githubusercontent.com/32881239/51777041-7251f580-20c9-11e9-973f-f08a3b9d045b.png">

**Comment by RyanCaruthers** [comment]
Sounds good @mjabbink !! I agree. 

@alisonjoseph  ONLY IMPACT CARDS that show up at bottom of Landing page and that are on the actual Impact page.

Thanks!

**Comment by alisonjoseph** [comment]
@RyanCaruthers what about the larger cards at mobile, should the font go smaller there?

**Comment by RyanCaruthers** [comment]
I agree with @mjabbink I think taking size from 20 down to 16 across all breakpoints should work! Lets try that
