### ISSUE TITLE
[Footer]: spacing between type and rule should be the same

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#197]
the spacing for all these should be same including the space between type and the color (top one: Privacy)

![img_2290](https://user-images.githubusercontent.com/32881239/51789657-32d2ea00-2159-11e9-80d0-b482cc384fad.JPG)

**Comment by alisonjoseph** [comment]
**needs to be updated in website addons**

**Comment by alisonjoseph** [comment]
Just wanted to confirm exact spacing I need to update here, the footer was built from Chiu's sketch file. https://github.com/carbon-design-system/carbon-website/issues/472  cc @designertyler @jeanservaas 
<img width="548" alt="screen shot 2019-01-28 at 8 56 45 am" src="https://user-images.githubusercontent.com/2753488/51844392-c8e24e00-22da-11e9-84f6-f8f1b0cf904d.png">

**Comment by jeanservaas** [comment]
Chiu has it as 96px below "Copyright..."

**Comment by alisonjoseph** [comment]
"spacing between all of these should be the same" --- was confusing. all of what? I can add more spacing below to match Chius file, and fix the top padding above Privacy. Wasn't sure if there was something else I was missing.

**Comment by mjabbink** [comment]
![screen shot 2019-01-28 at 7 59 01 pm](https://user-images.githubusercontent.com/32881239/51876617-33c17280-2337-11e9-92f0-94e9ad95a893.png)

**Comment by alisonjoseph** [comment]
Thanks for clarifying 😃
