### ISSUE TITLE
[Footer[ right side copy should break after “open”

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#202]
<img width="331" alt="screen shot 2019-01-26 at 11 34 50 am" src="https://user-images.githubusercontent.com/32881239/51790069-b3e0b000-215e-11e9-862d-9a85763416a6.png">

**Comment by mjabbink** [comment]
@alisonjoseph same for Carbon too.

**Comment by mjabbink** [comment]
@alisonjoseph — the fixes you did for slash design should also be same in Carbon and DL.

**Comment by alisonjoseph** [comment]
fixed in Carbon and here. Yes to creating an issue for IDL
