### ISSUE TITLE
[Tablet] main body column seems too wide 

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#203]
Should be same as Carbon and DL. @RyanCaruthers @alisonjoseph 

Should be around the halfway point of the black container

<img width="982" alt="screen shot 2019-01-26 at 11 33 59 am" src="https://user-images.githubusercontent.com/32881239/51790284-fefbc280-2160-11e9-94e3-e2fafb3e1eef.png">

**Comment by alisonjoseph** [comment]
Double checked sketch file and looks like these should be 6 columns at tablet not 8, I'll update across the site.

**Comment by RyanCaruthers** [comment]
I have them at 5 columns wide on tablet. see attached...


<img width="644" alt="screen shot 2019-01-26 at 1 38 52 pm" src="https://user-images.githubusercontent.com/46679352/51791892-d202dc00-216f-11e9-9210-2dfcdaf29927.png">

**Comment by alisonjoseph** [comment]
Do they not have the extra spacing to the right at tablet?

**Comment by RyanCaruthers** [comment]
Hmmm, i see what you mean with that example. I think that specific case with that larger paragraph copy style we should expand to the 6th column. but 5 columns is best for the example i showed where it has the quotes to the side.

**Comment by RyanCaruthers** [comment]
And to Mike's comment 5 columns looks best for the smaller body copy styles, that sm,aller type expanding past 5 columns is too long of a reading length

**Comment by alisonjoseph** [comment]
I updated everywhere to 5 and it looks better 👍  will be in my PR as soon as I can fix the failing tests

**Comment by RyanCaruthers** [comment]
sweetness!
