### ISSUE TITLE
[browser tab favicon]: needs to be “eye” UI icon

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#207]
@RyanCaruthers I think you wanted this to be the eye icon. I think that’s cool too. I’m also ok with the “bee” as IDL has. I lean on eye too though. I think Carbon keeps their favicon and in future if called IBM Design System (maybe that is internal one) and that could be the “bee” at that point. It’s still unclear but now Carbon remains and carbon favicon remains.

**Comment by mjabbink** [comment]
@RyanCaruthers but the vertical rebus can remain as the homepage icon just like the internal design site has now. I think that’s doable given I see the w3 favicon there now but rebus for home page app icon and start up (which is big at the moment).

**Comment by alisonjoseph** [comment]
duplicate #23 I need a 32x32 png of the image you want to use @RyanCaruthers

**Comment by RyanCaruthers** [comment]
ok sounds good Alison i will provide. Gonna close this issue and respond back to #23
