### ISSUE TITLE
[Approach nav menu]: sentence case

### ISSUE THREAD

**Issue by mbiyimoh** [IBM-Design/design-website#225]
I know I asked yall to capitalize Philosophy, Thinking and Services in the Approach dropdown menu, but my content reviewers reminded me that IBM style guides mandate the use of sentence case in the nav.

With that in mind, we need to _lowercase_  philosophy, thinking and services in that dropdown menu, the way they were before (Design stays capitalized of course).

FWIW, I don't personally agree with that choice stylistically, but I'm not important enough for that to matter 🤷‍♂️

**Comment by alisonjoseph** [comment]
I'll update! fwiw, I made them sentence case because I was following the guidelines. 😉  (we also recently did a sweep of the Carbon site annd updated everything to sentence case)

**Comment by mbiyimoh** [comment]
@alisonjoseph you da real mvp!! preciate you :)
