### ISSUE TITLE
Vertical Spacing issues on sections throughout site from where Anchor links land on page

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#227]
See attached... Needs to be 32px, these attached seem tight still.

<img width="634" alt="screen shot 2019-01-28 at 11 07 17 am" src="https://user-images.githubusercontent.com/46679352/51853196-5169ea00-22ed-11e9-8fda-31168c1b045f.png">
<img width="1051" alt="screen shot 2019-01-28 at 11 07 30 am" src="https://user-images.githubusercontent.com/46679352/51853197-5169ea00-22ed-11e9-9ac1-73e904477b51.png">
<img width="1230" alt="screen shot 2019-01-28 at 11 07 40 am" src="https://user-images.githubusercontent.com/46679352/51853198-5169ea00-22ed-11e9-84f7-9b18b1ffff7e.png">
<img width="1139" alt="screen shot 2019-01-28 at 11 07 54 am" src="https://user-images.githubusercontent.com/46679352/51853199-5169ea00-22ed-11e9-98ed-718e039c0075.png">
<img width="1157" alt="screen shot 2019-01-28 at 11 08 03 am" src="https://user-images.githubusercontent.com/46679352/51853201-5169ea00-22ed-11e9-9d1d-a741cf2a98ec.png">

**Comment by alisonjoseph** [comment]
this was updated already. (might need to clear your cache)
