### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by alisonjoseph** [IBM-Design/design-website#23]
Need 32x32 png from design for favicon

**Comment by RyanCaruthers** [comment]
Hey @mjabbink where can i get the correct favicon for this? We decided on the Most current "Eye" correct?

**Comment by RyanCaruthers** [comment]
@alisonjoseph try this!, i also slacked it to ya.


[eye_favicon_32px.svg.zip](https://github.com/IBM-Design/design-website/files/2813262/eye_favicon_32px.svg.zip)

**Comment by alisonjoseph** [comment]
added to my tile PR
