### ISSUE TITLE
Approach Design Thinking page: Scale up a couple icons optically

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#236]
Please scale these three icons up 2px proportionately from where they currently are, so they are optically the same size as the icons surrounding them.

![screen shot 2019-01-28 at 2 09 30 pm](https://user-images.githubusercontent.com/46679352/51863445-a2d2a300-2306-11e9-8895-1ff3386b6ab6.png)
![screen shot 2019-01-28 at 2 09 34 pm](https://user-images.githubusercontent.com/46679352/51863446-a2d2a300-2306-11e9-86e3-d7bd33753399.png)
![screen shot 2019-01-28 at 2 09 40 pm](https://user-images.githubusercontent.com/46679352/51863447-a2d2a300-2306-11e9-82f7-1b1470837bf8.png)

**Comment by alisonjoseph** [comment]
There is no way to target these specifically, will need to update svgs.

**Comment by designertyler** [comment]
I re-uploaded the svg's to be the size they are in the design specs. It looks like they are being resized to fit a 48px width.

**Comment by alisonjoseph** [comment]
I'll take a look
