### ISSUE TITLE
[Impact] Plex card

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#244]
we can remove the word "design" in the title.

![screen shot 2019-01-28 at 9 10 27 pm](https://user-images.githubusercontent.com/32881239/51879402-42148c00-2341-11e9-899d-1fd0795074d1.png)

**Comment by mjabbink** [comment]
@RyanCaruthers ask jeannie’s opinion too but think the rt. margin could increase a touch to keep these title less wide

**Comment by RyanCaruthers** [comment]
@mjabbink Yeah I agree. Ill sync with her in the morning!

**Comment by alisonjoseph** [comment]
I think on Carbon there is a 30% (?) right padding inside of the tiles/cards, not sure if its at all breakpoints or not. I'll be working on the tile updates this morning, so let me know and I can add the update in.

**Comment by RyanCaruthers** [comment]
@alisonjoseph just wrapped with Jeanner on this and here is what we want to implement. 

MAX = 30% padding on right side
XLG = 30% padding on right side
M = 30% padding on right side
MOBILE = 30% padding on right side

L = 0% zero

Thanks!
