### ISSUE TITLE
Landing page Video layout

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#247]
The video playing across the black and white split background is a little jarring, so we are moving the black background down a little bit past the frame of the video.... see attached...

![screen shot 2019-01-29 at 10 53 08 am](https://user-images.githubusercontent.com/46679352/51925319-68bfda80-23b4-11e9-92fa-0843a45b2889.png)
![screen shot 2019-01-29 at 10 53 18 am](https://user-images.githubusercontent.com/46679352/51925320-68bfda80-23b4-11e9-89cd-2dfd8120dd59.png)
![screen shot 2019-01-29 at 10 53 26 am](https://user-images.githubusercontent.com/46679352/51925321-69587100-23b4-11e9-8cc0-ca89d4785d14.png)

**Comment by alisonjoseph** [comment]
@jnm2377 want to add this to your video PR? Should be able to just change the background to black instead of black-white. Then we can also remove any references to black-white in the grid component and css.

**Comment by RyanCaruthers** [comment]
SWEET!!! lol
