### ISSUE TITLE
[Hamburger and IBM Design] in mobile the hover touches the type. 

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#248]
I think the type needs to move to the right. See Carbon and IDL in mobile for spacing between hamburger and type.

<img width="152" alt="screen shot 2019-01-29 at 11 58 07 am" src="https://user-images.githubusercontent.com/32881239/51925556-57c79700-23bd-11e9-8eea-2a68d919e7b5.png">

**Comment by mjabbink** [comment]
<img width="371" alt="screen shot 2019-01-29 at 12 00 01 pm" src="https://user-images.githubusercontent.com/32881239/51925636-7e85cd80-23bd-11e9-945d-2ae23998c57c.png">


<img width="371" alt="screen shot 2019-01-29 at 12 00 01 pm" src="https://user-images.githubusercontent.com/32881239/51925646-85144500-23bd-11e9-8b9d-8164d3763e3e.png">

**Comment by alisonjoseph** [comment]
Agree this looks weird now. How many pixels, 8? This was just updated to remove 16px of space to the left across Carbon and this site.

**Comment by alisonjoseph** [comment]
Tagging @jeanservaas  and @RyanCaruthers to make sure we are all on the same page here since Mike is asking to add back the padding I just removed yesterday. 😸

**Comment by alisonjoseph** [comment]
Got it 👍

**Comment by RyanCaruthers** [comment]
I agree with @jeanservaas comment. All good here! yay!
