### ISSUE TITLE
MOBILE ONLY Landing page and Impact Page: moving everything up 

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#255]
@mjabbink wondering if we should move up on mobile so you can see that there is a auto video playing on landing page in MOBILE, and move up things on Impact page to see there is more info below, since these two situations dont have anchor links to indicate there is more below?

see attached layout example....

![screen shot 2019-01-30 at 8 22 15 am](https://user-images.githubusercontent.com/46679352/51987860-f8bf5c00-2468-11e9-9cbc-52d43901aeb4.png)
![screen shot 2019-01-30 at 8 23 13 am](https://user-images.githubusercontent.com/46679352/51987861-f8bf5c00-2468-11e9-9abb-089cdbb03a9f.png)

**Comment by alisonjoseph** [comment]
There is also a bug on mobile right now where its taller than it should be, just an FYI if anyone is looking at it and notices the text getting cut off.

**Comment by mjabbink** [comment]
I don’t think I get what this issue is?

**Comment by RyanCaruthers** [comment]
@alisonjoseph I just chatted with Mike about this on Slack snd he agrees with the move im trying to make on Mobile with the above. Just so ya know. lets keep pursuing this change. Thanks!

**Comment by RyanCaruthers** [comment]
@alisonjoseph Mike and I chatted about the top of the video on mobile hitting at the same height as the anchor links do on other pages... see attached...


<img width="275" alt="screen shot 2019-01-30 at 3 22 44 pm" src="https://user-images.githubusercontent.com/46679352/52013591-17424900-24a3-11e9-9144-f8fc18b71d60.png">
<img width="274" alt="screen shot 2019-01-30 at 3 23 07 pm" src="https://user-images.githubusercontent.com/46679352/52013592-17424900-24a3-11e9-9938-47c666cdb48f.png">
<img width="274" alt="screen shot 2019-01-30 at 3 23 22 pm" src="https://user-images.githubusercontent.com/46679352/52013594-17dadf80-24a3-11e9-9370-fff9fa972381.png">
