### ISSUE TITLE
Type size on Cards across site....

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#256]
@alisonjoseph it looks like there was a little mis-communication on this issue before.

ONLY the Impact cards type should be the size 16. See attached...

![screen shot 2019-01-30 at 8 58 56 am](https://user-images.githubusercontent.com/46679352/51989887-8d2bbd80-246d-11e9-876a-cc1e9e5c74a6.png)

All other cards should go back to size 20. See attached...

![screen shot 2019-01-30 at 8 57 30 am](https://user-images.githubusercontent.com/46679352/51989901-9452cb80-246d-11e9-984f-bfa5ece37adf.png)
![screen shot 2019-01-30 at 8 57 41 am](https://user-images.githubusercontent.com/46679352/51989902-9452cb80-246d-11e9-9fc1-7967ef612da9.png)
![screen shot 2019-01-30 at 8 57 59 am](https://user-images.githubusercontent.com/46679352/51989903-9452cb80-246d-11e9-943f-2d0529b77893.png)

**Comment by alisonjoseph** [comment]
Hmm, ok those are using the exact same component right now, so will need to add something so we can style them differently.

**Comment by RyanCaruthers** [comment]
ah ok understood. Yeah we really only need the smaller 16 size on the Impact button situations where there is a lot more type in the headlines.
