### ISSUE TITLE
Add correct videos

### ISSUE THREAD

**Issue by alisonjoseph** [IBM-Design/design-website#27]
Need vimeo links for all pages

**Comment by RyanCaruthers** [comment]
Here are the correct links to pull each of the four videos from on the site:

Landing Page Sizzle reel:
https://vimeo.com/304672438

[Approach] Design Philosophy page:
https://vimeo.com/313055439

[Approach] Design Thinking page:
https://vimeo.com/303560967/c6d41539cd

[Approach] Design Services page:
https://www.youtube.com/watch?v=J727tCXTggk

**Comment by alisonjoseph** [comment]
Are these uploaded to the same account with the same settings as the demo video we have up now? Its not allowing me to update certain settings.  Might also need to upload the last video to youtube if you don't want it to look like a youtube embed. 

If you send me Vimeo login I can help research, but this is my first time working with embeds from them so I'm not sure off the top of my head.

Exact same embed code except video id, see the difference. 
<img width="805" alt="screen shot 2019-01-24 at 7 31 12 am" src="https://user-images.githubusercontent.com/2753488/51681385-0cbb1780-1faa-11e9-85d4-dc02516b31bf.png">

**Comment by alisonjoseph** [comment]
https://vimeo.com/blog/post/how-to-embed-your-gorgeous-videos-across-the-nets
