### ISSUE TITLE
Feedback for us

### ISSUE THREAD

**Issue by sstrubberg** [IBM-Design/design-website#274]
![image](https://user-images.githubusercontent.com/15822070/52080120-ad867580-255c-11e9-9001-0a6256e177ea.png)

Where should we point people to? Since we are making the repo private or moving it all together behind the firewall, where should we send people with questions and comments? ibmdesign@us.ibm.com?

**Comment by kellychurchill** [comment]
I don't think we should make it private at this point, since we are so close to launch date. 

We can also definitely use ibmdesign@us.ibm.com - I own and regularly check that mailbox.

**Comment by sstrubberg** [comment]
Let's do that then. Based on Phil's response to us using public github, i don't want to point non-IBMer to this repo.
