### ISSUE TITLE
teams page: Co-creation content

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/design-website#280]
Co-creator accuracy and tone and voice. 
### When users are intimately involved in the design process, you’re all but guaranteed to create something they love.
Human-centered (note the change to Humans instead of users) design goes far beyond just speaking with a few people before you get started; it’s about truly co-creating with your business users and stakeholders by making them integral members of the team. (Co-creation as Ginni uses it or any design thinker would say is not about making stakeholders of the team, but bringing clients and users in. So much so we've instantiated that practice as one of our Enterprise Design Thinking key, link to Sponsor Users.)  

From the initial visioning stages through to delivery and beyond, we work closely with both of these groups to ensure that every decision we make is rooted in a deep understanding of their needs. (commentary... indeed we work closely with stakeholder but not truly as co-creation, but through Playbacks, yet another Key of EDT)

**Comment by mbiyimoh** [comment]
@air2h2o thanks for the feedback – will swap "user-centered" for "human-centered" and will change, "by making them integral members of the team" to "by involving them in the design process from Day 1."
