### ISSUE TITLE
Coremetrics and tags for ibm.com

### ISSUE THREAD

**Issue by kellychurchill** [IBM-Design/design-website#283]
We are going to have to add in tags and site analytics for ibm.com

Instructions here:
https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/Wa243ec02272e_4b3e_a526_6cff063f94c0/page/Tag%20Management

Would like to do a page load test before and after adding these analytics scripts

**Comment by alisonjoseph** [comment]
My vpn has stopped working so I can't see the instructions for this. I can look at it next week, unless there is someone you think has time before that?

**Comment by kellychurchill** [comment]
Next week is fine

**Comment by alisonjoseph** [comment]
I tried looking at this and got lost in their docs. Do we know anyone who has experience adding this who can help out?

**Comment by kellychurchill** [comment]
We pulled in metrics from IDL site and tested performance in Lighthouse.  

Need to investigate options which do not impact performance as greatly as these scripts do.

<img width="998" alt="screen shot 2019-02-22 at 2 45 09 pm" src="https://user-images.githubusercontent.com/2744778/53270624-e0321280-36b1-11e9-8122-34a9e99ce6e3.png">
<img width="988" alt="screen shot 2019-02-22 at 2 44 26 pm" src="https://user-images.githubusercontent.com/2744778/53270625-e0321280-36b1-11e9-8323-1bb367d71391.png">
