### ISSUE TITLE
Carousel: Sidescrolling bug

### ISSUE THREAD

**Issue by sstrubberg** [IBM-Design/design-website#284]
Only able to recreate this in Chrome.

![jan-31-2019 19-52-42](https://user-images.githubusercontent.com/15822070/52097759-e42ab300-2591-11e9-9215-02bfd4feb1ff.gif)

**Comment by alisonjoseph** [comment]
How did you do that? I can't recreate. 👀

**Comment by sstrubberg** [comment]
I start side-scrolling on the image. It only happens on the 3rd or 4th dot i think..

**Comment by jnm2377** [comment]
Hmm.. I can't recreate either. My local env is working fine in chrome.

**Comment by alisonjoseph** [comment]
Yea I just noticed the backwards slide bug thing
