### ISSUE TITLE
FIND YOUR TEAM: copy scale bug

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#285]
the small two lines of body copy should be the larger size of the copy above it, for some reason it got smaller and tight vertical spacing applied to it. see attached image of incorrect type...

![screen shot 2019-02-01 at 7 53 06 am](https://user-images.githubusercontent.com/46679352/52127129-d3f8ef00-25f6-11e9-8983-8c9dc689bf54.png)

What it should look like....

![screen shot 2019-02-01 at 7 57 49 am](https://user-images.githubusercontent.com/46679352/52127228-1c181180-25f7-11e9-8dc4-7132955bc4a6.png)

**Comment by alisonjoseph** [comment]
A closing tag got missed somehow when a copy edit got made. I'm on it!

**Comment by RyanCaruthers** [comment]
sounds great! thanks!
