### ISSUE TITLE
Busted links

### ISSUE THREAD

**Issue by sstrubberg** [IBM-Design/design-website#296]
- [ ] Teams:

![image](https://user-images.githubusercontent.com/15822070/52133026-2db4e580-2606-11e9-9dd0-df37844aa75f.png)

- [x] ~Practices:~

![image](https://user-images.githubusercontent.com/15822070/52133083-458c6980-2606-11e9-8b86-6e0c826b2137.png)

**Comment by alisonjoseph** [comment]
The links on the approach sub pages are fixed in my PR

**Comment by alisonjoseph** [comment]
@mbiyimoh do you have the link for open roles on the teams page?

**Comment by alisonjoseph** [comment]
I'll add the digital link https://www.ibm.com/standards/web/
