### ISSUE TITLE
[home page] lead copy width

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#309]
<img width="701" alt="screen shot 2019-02-01 at 10 52 17 am" src="https://user-images.githubusercontent.com/32881239/52143182-a66c6f80-260f-11e9-8b64-bc96cedd0e7f.png">

**Comment by mjabbink** [comment]
<img width="716" alt="screen shot 2019-02-01 at 10 52 09 am" src="https://user-images.githubusercontent.com/32881239/52143233-c6039800-260f-11e9-9bab-eb4139850eea.png">

**Comment by alisonjoseph** [comment]
currently spans 8 columns at large, and 5 columns at medium breakpoint but is missing the % padding to the side the other paragraphs have. Is this the issue?

**Comment by RyanCaruthers** [comment]
Yeah should be the 7.5 column span at large instead of 8, which should bump "the" down to next line.

Thanks!

**Comment by mjabbink** [comment]
yes, and give appearance of that subtle padding that jut makes type feel more comfortable rather than spanning full widths.

thanks!
