### ISSUE TITLE
Approach Services Child Page: Character update

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#313]
Change Em dashed to EN DASHES and add a space before the word.... see attached of what it should look like. Thanks!

<img width="1109" alt="screen shot 2019-02-01 at 4 47 09 pm" src="https://user-images.githubusercontent.com/46679352/52153875-60c89a80-2641-11e9-9fbc-9faf2b00cd31.png">

**Comment by jnm2377** [comment]
@mbiyimoh if you're submitting a PR for #315 do you wanna go ahead and include this in there?
