### ISSUE TITLE
[Philosophy page]: First sidebar copy replace "en dash" with "em dash"

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#315]
between ... before—maybe...

<img width="314" alt="screen shot 2019-02-03 at 5 22 02 pm" src="https://user-images.githubusercontent.com/32881239/52183693-7a501a80-27d8-11e9-8f3a-40f72aac2240.png">

**Comment by RyanCaruthers** [comment]
Yeah looks like those do need to change to em dashes. @alisonjoseph do you need @mbiyimoh to submit content PRs for these today? just let us know whats easier for the dev side. Thanks!
