### ISSUE TITLE
Video at top (with audio) autostarts when launching another video. 

### ISSUE THREAD

**Issue by kellychurchill** [IBM-Design/design-website#342]
## Title line template: [Title]: Brief description
Video at top (with audio) autostarts when launching another video. 

## Detailed description

> What browser are you working in?
Safari Version 12.0.2 (14606.3.4)

## Steps to reproduce the issue

To reproduce: 
Safari Version 12.0.2 (14606.3.4)
Load https://wwwpoc.ibm.com/design/
Scroll down and click the middle video, "Video: Building a security operations center on wheels". 
The target video opens in a new tab. Meanwhile, in the original tab, the soundtrack of the main video ("At IBM, "Goof design" is not only a requirement") starts playing.

**Comment by sstrubberg** [comment]
This happens on both the Security link *and* the Typeface competition link. Something about leaving the page starts the sizzle video..
