### ISSUE TITLE
SAFARI: Approach Philosophy Page: IDL button not working

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#343]
On Safari, when you scroll down Approach Philosophy page and click the "IBM Design Language" button you get an error message.

![screen shot 2019-02-07 at 12 41 16 pm](https://user-images.githubusercontent.com/46679352/52435163-bdf79c80-2ad6-11e9-9e76-89d3a09c9678.png)
![screen shot 2019-02-07 at 12 41 27 pm](https://user-images.githubusercontent.com/46679352/52435164-bdf79c80-2ad6-11e9-8ce1-252cf2f2daa4.png)

**Comment by alisonjoseph** [comment]
not related to this site, should be working now
