### ISSUE TITLE
Video should have a button to mute sound 

### ISSUE THREAD

**Issue by kellychurchill** [IBM-Design/design-website#349]
The video sizzle reel does not have a way to mute the sound without turning off your computer speakers.

**Comment by alisonjoseph** [comment]
Is this a vimeo setting we can turn on @sstrubberg ?

**Comment by jnm2377** [comment]
This would definitely require having the regular vimeo UI controls. The minimal vimeo controls just allows for pause/play and expand, which is what we have now. Their regular UI, I believe allows for volume control plus progress bar control as well. This can be updated in the vimeo settings though, I didn't do anything for that.

**Comment by alisonjoseph** [comment]
We should leave as-is. They definitely don't want the regular vimeo controls. Did this request come from someone specific @kellychurchill ?

**Comment by alisonjoseph** [comment]
closing in favor of #355
