### ISSUE TITLE
Design Practices section: Add tile and copy for Accessibility

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#446]
Screeshot for placement reference:
<img width="467" alt="Screen Shot 2020-05-12 at 2 52 21 PM" src="https://user-images.githubusercontent.com/46679352/81738981-34184b00-9460-11ea-869a-5fddda6c6f87.png">

Body copy here:
Resources and guidance crafted by IBM’s accessibility experts to help any product team deliver an accessible solution to the market. 

Card image attached here:
![Accessibility_BeEqual_card_image](https://user-images.githubusercontent.com/46679352/81739073-50b48300-9460-11ea-95cf-03c6aebc53ea.png)

**Comment by RyanCaruthers** [comment]
Will link to here:
https://www.ibm.com/able/

**Comment by andreancardona** [comment]
I'll take this on @RyanCaruthers

**Comment by RyanCaruthers** [comment]
Thanks!

**Comment by andreancardona** [comment]
- [ ] done

**Comment by RyanCaruthers** [comment]
@andreancardona I forgot to add the tile image for mobile. See attached...
![Be_Equal_mobile](https://user-images.githubusercontent.com/46679352/81842483-b01e9b80-9511-11ea-9917-6e424d889733.png)
