### ISSUE TITLE
Switcher List: IBM Accessibility to top group

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#448]
screenshot for placement reference:
<img width="759" alt="Screen Shot 2020-05-12 at 2 57 17 PM" src="https://user-images.githubusercontent.com/46679352/81739386-e51ee580-9460-11ea-9bb5-8015684031a3.png">

**Comment by RyanCaruthers** [comment]
Will link to here:
https://www.ibm.com/able/

**Comment by andreancardona** [comment]
I'll take this on @RyanCaruthers

**Comment by andreancardona** [comment]
- [ ] done

**Comment by RyanCaruthers** [comment]
Thank you!
