### ISSUE TITLE
[Approach sub pages]: Banner height

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#71]
I think the height should be 528px for Design Philosophy, Design Thinking, Design Services page banners and any other banner that can be this size.

**Comment by mjabbink** [comment]
<img width="1244" alt="screen shot 2019-01-18 at 5 12 37 pm" src="https://user-images.githubusercontent.com/32881239/51415578-48865500-1b44-11e9-9588-647380d44f5a.png">

**Comment by mjabbink** [comment]
This also applies to the same banners in Approach Overview page with all three (Philosophy, Thinking, Services)

**Comment by mjabbink** [comment]
Also above just noticed the to paragraphs under "Design thinking framework" should be not extend into the fifth column on grid. Basically stay in the same set of columns that "Principles" sits in below in the next container. @RyanCaruthers hope this make sense?

**Comment by RyanCaruthers** [comment]
@mjabbink yeah makes sense to me! we will adjust that.

**Comment by mjabbink** [comment]
Made a mistake here when calling 528. Should be 560. Apologies if you already made this change.

**Comment by RyanCaruthers** [comment]
All good they are at 560 now in latest sketch file.

**Comment by RyanCaruthers** [comment]
@sstrubberg @alisonjoseph All banners have updated to 560px High across the site. See attached images. Approach Page, Approach Child page headers, and Impact child page headers...
![screen shot 2019-01-22 at 8 04 47 am](https://user-images.githubusercontent.com/46679352/51540694-b4a2da80-1e1c-11e9-9dd2-efdc809f3673.png)
![screen shot 2019-01-22 at 8 05 04 am](https://user-images.githubusercontent.com/46679352/51540695-b53b7100-1e1c-11e9-9f30-ea42224557f6.png)
![screen shot 2019-01-22 at 8 05 27 am](https://user-images.githubusercontent.com/46679352/51540697-b53b7100-1e1c-11e9-8235-9f1ea80dd4b3.png)

**Comment by alisonjoseph** [comment]
@RyanCaruthers Is this only for desktop? What should size be for mobile/tablet?

**Comment by RyanCaruthers** [comment]
Yes, this is desktop, Working on mobile and desktop now... will share here asap.

**Comment by RyanCaruthers** [comment]
Ok @alisonjoseph Tablet heights will be 336px across all, and Mo
![screen shot 2019-01-22 at 9 19 25 am](https://user-images.githubusercontent.com/46679352/51545269-3bf54b80-1e27-11e9-9375-6fe3eb66de96.png)
![screen shot 2019-01-22 at 9 19 39 am](https://user-images.githubusercontent.com/46679352/51545272-3dbf0f00-1e27-11e9-8f47-03f26e9c24d1.png)

bile will be 480px across all. See attached..

**Comment by RyanCaruthers** [comment]
Im working on final artwork inside those containers now, but wanted to get you the heights.

**Comment by mjabbink** [comment]
the banner should be same as Carbon site.

![screen shot 2019-01-22 at 6 58 46 pm](https://user-images.githubusercontent.com/32881239/51573621-22302480-1e78-11e9-8552-59cf932d5b1f.png)

**Comment by mjabbink** [comment]
@RyanCaruthers The 80px seems large for tablet above large banner no?
