### ISSUE TITLE
[Landing page]: Rebus a bit small

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#72]
I think the rebus could go to 72px tall. @RyanCaruthers what do you think. 

It also needs to move down closer to the Type. I believe Ryan specifies 32 px.

**Comment by RyanCaruthers** [comment]
@mjabbink yes 72px works and yes 32px above the type.

**Comment by mjabbink** [comment]
Also move to the right 8px. 

![screen shot 2019-01-22 at 1 05 43 pm](https://user-images.githubusercontent.com/32881239/51555794-78846f80-1e46-11e9-8dd7-e363b1b765e7.png)

**Comment by mjabbink** [comment]
![screen shot 2019-01-22 at 1 08 45 pm](https://user-images.githubusercontent.com/32881239/51555960-e0d35100-1e46-11e9-8bba-e93b7c01a199.png)

**Comment by RyanCaruthers** [comment]
@mjabbink @alisonjoseph Yes i agree with this move, lets apply it.
