### ISSUE TITLE
[Practices]: Large banner aspect ratio

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#73]
The three large billboard banners for Language, EDT and Research should be 16:9 aspect ratio

<img width="1045" alt="screen shot 2019-01-18 at 8 43 42 pm" src="https://user-images.githubusercontent.com/32881239/51420632-cad14200-1b61-11e9-8f68-55f7062ddacd.png">

<img width="1045" alt="screen shot 2019-01-18 at 8 40 45 pm" src="https://user-images.githubusercontent.com/32881239/51420616-affecd80-1b61-11e9-8a01-cb86f68e1bcd.png">

<img width="1047" alt="screen shot 2019-01-18 at 8 43 49 pm" src="https://user-images.githubusercontent.com/32881239/51420633-d0c72300-1b61-11e9-8c21-092a5e3ba2ba.png">

**Comment by mjabbink** [comment]
And a 1:1 svg for mobile version.

**Comment by RyanCaruthers** [comment]
this is done and they are now 16:9. yay!
