### ISSUE TITLE
[Approach] Bottom large banners

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#74]
See the bottom of the Watson site for same banner component at the bottom of each sub page in Approach.
https://msc-watson-64-qms6lkgtrcnynocvo1qetkrujywaeokg.tugboat.qa/watson/how-watson-is-different

These are what the bottom of the banner in Approach should be like and same height in xl breakpoints.

**Comment by alisonjoseph** [comment]
spec in #98
