### ISSUE TITLE
[Mobile] site should not move left and right. 

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#84]
zoom in and it holds zoom is ok. Zoom out to shrink and it snaps back to full screen.

This behavior:
https://design-language-new.w3ibm.mybluemix.net/design/language/elements/icon-library

-->

## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request, a bug, or a general issue?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by alisonjoseph** [comment]
there is a weird extra space to the right of the entire space, looking in to where it is coming from. Good catch!

**Comment by mjabbink** [comment]
I have to reload to get that space to go away.

**Comment by mjabbink** [comment]
true sense of a bug!

**Comment by alisonjoseph** [comment]
found the bug! its in the footer, the divider lines on mobile are wider than 100% 🐛
