### ISSUE TITLE
[Type Specs] First two paragraphs under lead space should be same weight.

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#85]
Seems like these two large type sizes are the same and I think they should be same weight.

<img width="960" alt="screen shot 2019-01-20 at 11 41 17 am" src="https://user-images.githubusercontent.com/32881239/51442238-daa76e00-1ca8-11e9-9c3c-e25a6af71cfe.png">

<img width="1069" alt="screen shot 2019-01-20 at 11 42 26 am" src="https://user-images.githubusercontent.com/32881239/51442240-ded38b80-1ca8-11e9-8b6c-0c3ae0c60b66.png">

**Comment by alisonjoseph** [comment]
Top paragraph is using `expressive-paragraph-01` token and bottom on is using `expressive-heading-04` . Just need to know which token to use for both. Tagging @jeanservaas for insight on when to use each token. Currently `<h2>` is using the heading-04 and `<p size="xl">` is using the paragraph-01.

**Comment by jeanservaas** [comment]
Try $expressive-paragraph-01 for both of those -- that's why we made that token, so we could have more control over those longer paragraphs and not tie them to our headings.

That's a new token so let me know how it works, we can play with it's values a little if we need to.

**Comment by mjabbink** [comment]
@RyanCaruthers needs to determine which weight he’s wanting to use. I lean on the lead for that size but can go either way. The point was not to have two weights for the same size but rock one weight with a vengeance. I think Ryan is leaning light but not sure.

**Comment by mjabbink** [comment]
which do you like @jeanservaas ? Light or Regs?

**Comment by mjabbink** [comment]
it’s for these moments as well...

<img width="678" alt="screen shot 2019-01-21 at 4 29 58 pm" src="https://user-images.githubusercontent.com/32881239/51502852-02c8c700-1da6-11e9-8cbe-4a02050e8b83.png">
<img width="588" alt="screen shot 2019-01-21 at 4 30 02 pm" src="https://user-images.githubusercontent.com/32881239/51502853-02c8c700-1da6-11e9-823d-6ed143422d6a.png">

**Comment by RyanCaruthers** [comment]
I like the Light weight across all.

**Comment by RyanCaruthers** [comment]
See attached, light weight in sketch file on right versus current in browser...
![screen shot 2019-01-22 at 8 36 36 am](https://user-images.githubusercontent.com/46679352/51542467-f0d83a00-1e20-11e9-88fa-16b6ba8e5c54.png)

**Comment by alisonjoseph** [comment]
Ok, just to confirm, will be switching all large type to the expressive-paragraph-01 token?

**Comment by RyanCaruthers** [comment]
This is what it has been called out as in sketch. I just know i want the light weight... So i may need your help figuring out what the actual token is...
![screen shot 2019-01-22 at 9 52 26 am](https://user-images.githubusercontent.com/46679352/51547383-c93a9f00-1e2b-11e9-876e-01d7b9c9f995.png)

**Comment by alisonjoseph** [comment]
Sketch has expressive-heading-04?

**Comment by alisonjoseph** [comment]
Ok, switching to expressive-paragraph0]-01 everywhere. that should give you want you want

**Comment by RyanCaruthers** [comment]
sounds good!

**Comment by mjabbink** [comment]
Some of those need headers in semibold

**Comment by alisonjoseph** [comment]
We don't have a token for semi-bold specifically, We're `<strong>` tags which will map to `font-weight: 600` as soon as I pull the latest update from elements, which should be semi-bold.
