### ISSUE TITLE
[Impact]: Horizontal rule dividers?

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#86]
@RyanCaruthers Think about adding rules between the projects. Seems like they’re needed and you do use it at the top across the pages after that secondary large type intro copy. You also use it in between the three Practices.

<img width="1449" alt="screen shot 2019-01-20 at 11 50 22 am" src="https://user-images.githubusercontent.com/32881239/51442333-c0ba5b00-1ca9-11e9-8f7e-c71de11a0f8f.png">

<img width="1458" alt="screen shot 2019-01-20 at 11 50 33 am" src="https://user-images.githubusercontent.com/32881239/51442330-bc8e3d80-1ca9-11e9-8bd4-f98c89a91003.png">

**Comment by mjabbink** [comment]
<img width="1449" alt="screen shot 2019-01-20 at 11 52 14 am" src="https://user-images.githubusercontent.com/32881239/51442371-da5ba280-1ca9-11e9-9eeb-60e291b72932.png">




<img width="1459" alt="screen shot 2019-01-20 at 11 43 33 am" src="https://user-images.githubusercontent.com/32881239/51442340-cb74f000-1ca9-11e9-891c-295b492f38cc.png">

**Comment by alisonjoseph** [comment]
spec provided here https://github.com/IBM-Design/design-website/issues/94
