### ISSUE TITLE
[anchor link arrows] align to baseline of big type or hang from cap height of big type

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/design-website#92]
<img width="1405" alt="screen shot 2019-01-21 at 6 57 40 pm" src="https://user-images.githubusercontent.com/32881239/51504356-8d152900-1dae-11e9-937c-a505e10fdbe9.png">

<img width="1308" alt="screen shot 2019-01-21 at 6 56 08 pm" src="https://user-images.githubusercontent.com/32881239/51504366-9d2d0880-1dae-11e9-949d-26e3be2e8ea8.png">

**Comment by RyanCaruthers** [comment]
@mjabbink YEah i just submitted an issue here for the headline relationship to the anchor links, what is your thought on the anchor links on Teams page halfway down? should they align to baseline of the larger copy to the left of them or to the top?
