### ISSUE TITLE
Card size across site

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/design-website#93]
All cards are supposed to be the same size across the site on desktop at 304px W X 152px H. Please follow these specs.
![screen shot 2019-01-22 at 8 11 40 am](https://user-images.githubusercontent.com/46679352/51541179-cc2e9300-1e1d-11e9-9073-670a4d7a687a.png)

They look quit larger in the browser compared to sketch file.

**Comment by alisonjoseph** [comment]
they are 4 columns wide on the grid, with the same aspect ratio. Are you saying they shouldn't follow the grid?
